# Generated by Django 2.2.3 on 2019-07-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dier',
                'verbose_name_plural': 'Dieren',
            },
        ),
        migrations.CreateModel(
            name='Doodsoorzaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Doodsoorzaak',
                'verbose_name_plural': 'Doodsoorzaken',
            },
        ),
        migrations.CreateModel(
            name='OnderliggendeOorzaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=255)),
                ('doodsoorzaak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Doodsoorzaak')),
            ],
            options={
                'verbose_name': 'Onderliggende oorzaak',
                'verbose_name_plural': 'Onderliggende oorzaken',
            },
        ),
        migrations.CreateModel(
            name='Gebeurtenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('locatie', models.CharField(max_length=255)),
                ('oorzaak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.OnderliggendeOorzaak')),
            ],
            options={
                'verbose_name': 'Gebeurtenis',
                'verbose_name_plural': 'Gebeurtenissen',
            },
        ),
        migrations.CreateModel(
            name='Slachtofferaantal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.IntegerField(blank=True, null=True)),
                ('schatting', models.CharField(blank=True, max_length=16, null=True)),
                ('dier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Dier')),
                ('gebeurtenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Gebeurtenis')),
            ],
            options={
                'verbose_name': 'Slachtofferaantal',
                'verbose_name_plural': 'Slachtofferaantallen',
                'unique_together': {('gebeurtenis', 'dier')},
            },
        ),
    ]
